# Generated by Django 4.2 on 2023-04-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='rasm2',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='rasm3',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
